// <auto-generated />
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20251126070112_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = "75924CFB-EB28-4016-89B6-FAA77426B2BD",
                            Amount = 10,
                            Description = "Mechanical keyboard promo",
                            ProductName = "Discounted Keyboard"
                        },
                        new
                        {
                            Id = "021572B8-F35F-4BAE-B806-B076AFA1263D",
                            Amount = 20,
                            Description = "20% off wireless mouse",
                            ProductName = "Wireless Mouse"
                        },
                        new
                        {
                            Id = "498C900E-3EFD-4988-8135-F3E849C8EF34",
                            Amount = 5,
                            Description = "Buy 1 take 1 USB-C cable",
                            ProductName = "USB-C Cable"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
